# Copy this file to .github/workflows/ci.yml in each repo
name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    uses: barazo-forum/.github/.github/workflows/reusable-ci.yml@main
    with:
      node-version: "24"
      run-build: true
