name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for Barazo? We'd love to hear it. Please describe the problem you're trying to solve and your proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve? Why is it needed?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think this should work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about?
    validations:
      required: false

  - type: dropdown
    id: repo
    attributes:
      label: Which component?
      options:
        - barazo-api (backend)
        - barazo-web (frontend)
        - barazo-lexicons (schemas)
        - barazo-deploy (Docker/hosting)
        - barazo-website (docs site)
        - Not sure
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and this hasn't been requested yet
          required: true
